services:
  api:
    image: node:12.18.4
    working_dir: /code
    container_name: kahnoot_test_api
    environment: 
      - PGUSER=kahnoot
      - PGHOST=db
      - PGPASSWORD=five
      - PGDATABASE=leaderboard_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run test"
    tty: true
  db:
    image: postgres:latest
    container_name: kahnoot_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=leaderboard_test
      - POSTGRES_USER=kahnoot
      - POSTGRES_PASSWORD=five
volumes:
  test_db:
networks: 
  default:
    name: kahnoot_test